const filmes = [
  {
    "tipo": "filme",
    "titulo": "À Beira do Abismo",
    "descricao": "Policial honesto é preso por um crime que não cometeu. Consegue fugir da prisão e, ameaçando cometer suicídio do alto de um edifício, envolve uma experiente negociadora da polícia em um plano para provar sua inocência.",
    "capa": "https://m.media-amazon.com/images/S/pv-target-images/70d25a006644288e51d94447fa726d2ce622971333076cb7577b12e8a388b985.jpg",
    "banner": "https://i.imgur.com/7yGxzzp.jpg",
    "categoria": "Ação / Thriller",
    "id": "1bWXVone_m1l9aJUYlQQXVd3enk3qp4we",
    "mostrarNoBanner": false,
    "prioridade": 1,
    "ano": 2012,
    "duracao": "1h 42min",
    "resolucao": "1080p"
  },
  {
    "tipo": "filme",
    "titulo": "Homem-Aranha no Aranhaverso",
    "descricao": "Miles Morales, um jovem do Brooklyn, é mordido por uma aranha radioativa e se torna o novo Homem-Aranha, descobrindo outras versões do herói de dimensões paralelas.",
    "capa": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuOzzY622bbROyH5LrdY8h8fNZZ6MRWU7nMcAdvnn1jQ&s=10",
    "banner": "https://i.imgur.com/fkqVbny.jpg",
    "categoria": "Animação / Aventura / Família",
    "id": "1oTn6HXod8EHS5JlBibnhjPSrqVhgNwjV",
    "mostrarNoBanner": false,
    "prioridade": 1,
    "ano": 2018,
    "duracao": "1h 56min",
    "resolucao": "4K"
  },
  {
    "tipo": "filme",
    "titulo": "Cruzeiro das Loucas",
    "descricao": "Dois amigos embarcam acidentalmente em um cruzeiro para o público gay e acabam vivendo uma jornada de autodescoberta e aceitação.",
    "capa": "https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/95/73/90/20425630.jpg",
    "banner": "https://i.imgur.com/6MbPNV5.jpg",
    "categoria": "Comédia / Romance",
    "id": "0ByfEzfBLMGseWUwydWk5YXZveEU",
    "mostrarNoBanner": false,
    "prioridade": 1,
    "ano": 2002,
    "duracao": "1h 34min",
    "resolucao": "720p"
  },
  {
    "tipo": "filme",
    "titulo": "Debi & Lóide: Dois Idiotas em Apuros",
    "descricao": "Dois amigos debilóides vão para Aspen tentar devolver uma maleta esquecida, mas acabam envolvidos em uma confusão milionária.",
    "categoria": "Comédia / Clássico",
    "ano": "1994",
    "duracao": "1h 53min",
    "resolucao": "1080p",
    "banner": "https://i.imgur.com/CuRuEZ7.jpg",
    "capa": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3jX2Dzr370H9xM9nawnmBXMXRg3FIFEgyE5o72pu2S7WV5AMwuiZvr1fWE86ib_D3RkGWu-BZDyA7BVJKSN8Eb5zA4GaWxzBApzrXcyIJ0A",
    "id": "0ByfEzfBLMGseS0ZjM25OQVl1TVE",
    "mostrarNoBanner": false,
    "prioridade": 1
  },
  {
    "tipo": "filme",
    "titulo": "Esposa de Mentirinha",
    "descricao": "Um cirurgião plástico convence sua melhor amiga a fingir ser sua esposa para impressionar uma nova namorada.",
    "capa": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKrNOSc_0t8mKxniBLfLgG9Ux72Z0paIaDOB4ukHabGw&s=10",
    "banner": "https://i.imgur.com/QLPRFW3.jpg",
    "categoria": "Comédia / Romance",
    "id": "1IKst0bCRXrKfx64QU3-SKIyOFfoYsBPb",
    "mostrarNoBanner": false,
    "prioridade": 1,
    "ano": 2011,
    "duracao": "1h 57min",
    "resolucao": "1080p"
  },
  {
    "tipo": "filme",
    "titulo": "A Coleção Invisível",
    "descricao": "Um jovem busca uma coleção de gravuras raras para salvar o antiquário de sua família, mas encontra uma história que muda sua visão de mundo.",
    "capa": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTip0pga7dPD6PkUXbbLK7IEUZpOGpkyUGEHWjfiPlF7Q&s=10",
    "banner": "https://i.imgur.com/Gswn24Z.jpg",
    "categoria": "Drama / Nacional",
    "id": "1e8joyTwZ9SUzK8YjIQNu7rk_ijJKsW_x",
    "mostrarNoBanner": false,
    "prioridade": 1,
    "ano": 2013,
    "duracao": "1h 30min",
    "resolucao": "1080p"
  },
  {
    "tipo": "filme",
    "titulo": "Pantera Negra",
    "descricao": "T’Challa retorna a Wakanda para assumir o trono após a morte de seu pai, mas enfrenta um inimigo que ameaça todo o reino.",
    "categoria": "Ação / Ficção Científica / Heróis",
    "ano": "2018",
    "duracao": "2h 14min",
    "resolucao": "4K",
    "banner": "https://upload.wikimedia.org/wikipedia/pt/2/24/Black_Panther_2018_poster.jpg",
    "capa": "https://br.web.img3.acsta.net/c_310_420/pictures/17/12/07/16/09/2291532.jpg",
    "id": "16qP5PXShxzr1lQuOyiUzbBdCoWSn6YHr",
    "mostrarNoBanner": false,
    "prioridade": 1
  },
  {
    "tipo": "filme",
    "titulo": "Thor: Ragnarok",
    "descricao": "Thor precisa escapar de um planeta distante e impedir o Ragnarok, a destruição de Asgard.",
    "categoria": "Aventura / Ficção Científica / Heróis",
    "ano": "2017",
    "duracao": "2h 10min",
    "resolucao": "4K",
    "banner": "https://i.imgur.com/LHt3g5q.jpg",
    "capa": "https://br.web.img3.acsta.net/pictures/17/08/26/00/05/175443.jpg",
    "id": "1rLgotI926KQiVjMs5DEXOffDnHoqvBaV",
    "mostrarNoBanner": false,
    "prioridade": 1
  },
  {
    "tipo": "filme",
    "titulo": "10 Coisas que Eu Odeio em Você",
    "descricao": "Kat e Bianca são irmãs opostas: uma não quer saber de romance, a outra sonha em namorar — mas só poderá fazê-lo se Kat encontrar um par primeiro.",
    "categoria": "Romance / Comédia",
    "ano": "1999",
    "duracao": "1h 37min",
    "resolucao": "1080p",
    "banner": "https://i.imgur.com/BhDFlcT.jpg",
    "capa": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAvOuddbilvDpGaQLwZJO_uVHLeNw5T6kjRBH1E8-0mrq7rBy1l9WawsYLfHELqsSV0yLX0chjWTyl9DzETXlovBqXGPZAFKmUvaQlqDxq",
    "id": "1abkKtm9MvEloFyU89MoTbNxZ6C9I2xfk",
    "mostrarNoBanner": false,
    "prioridade": 1
  },
  {
    "tipo": "anuncio",
    "titulo": "ErikFlix",
    "descricao": "",
    "categoria": "",
    "ano": "",
    "duracao": "",
    "resolucao": "",
    "banner": "https://i.imgur.com/FEXQZKV_d.webp?maxwidth=1520&fidelity=grand",
    "capa": "https://i.imgur.com/FEXQZKV_d.webp?maxwidth=1520&fidelity=grand",
    "id": "",
    "mostrarNoBanner": true,
    "prioridade": 3
  },
  {
    "tipo": "filme",
    "titulo": "Oito Mulheres e um Segredo",
    "descricao": "Recém-saída da prisão, Debbie Ocean logo procura sua ex-parceira Lou para realizar um elaborado assalto: roubar um colar de diamantes no valor de 150 milhões de dólares, que a empresa Cartier mantém em um cofre. O plano é convencer a organização a emprestá-lo para que a estrela Daphne Kluger use a joia no badalado Met Gala, um dos eventos mais chiques e vistosos de Nova York. Para tanto, Debbie e Lou reúnem uma equipe composta apenas por mulheres: Nine Ball, Amita, Constance, Rose e Tammy.",
    "categoria": "Comédia/Ação",
    "ano": "2018",
    "duracao": "1h 51m",
    "resolucao": "",
    "banner": "https://miro.medium.com/0*TNzLaogqaVSXpUjA.jpg",
    "capa": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmld1_CXNuv4LDkhoSFNDFtD0x4Bx_JGgkaZAt6uNXnw&s",
    "id": "17kZ5xZV5F98lFdZguupDlNK1Hfw_vaAZ",
    "mostrarNoBanner": true,
    "prioridade": 1
  },
  {
    "tipo": "filme",
    "titulo": "A Família Addams",
    "descricao": "Um homem que afirma ser Funério, o irmão desaparecido de Gomez Addams, chega à casa da família. No entanto, Funério não consegue se lembrar de detalhes de sua vida e Morticia começa a suspeitar que ele talvez seja uma fraude.",
    "categoria": "Comédia/Terror",
    "ano": "1991",
    "duracao": "1h 39m",
    "resolucao": "",
    "banner": "https://recreio.com.br/wp-content/uploads/filmes/familia_addams_capa.jpg",
    "capa": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrHvoQ5OYILXlN9BYIbY9c-3Ady-jZfvjvoLkknM0YgIlUuPpAVMnQeUQ&s=10",
    "id": "1EWOdJD1t5YTxgAgOPoaYbmC4Sb0aU1C1",
    "mostrarNoBanner": true,
    "prioridade": 1
  }
];